Repository brazil-data-cube/lccs-ws, pull requests merged in 2021-02, with the labels that each got.

#47 working in crud #14
  .drone.yml
  lccs_ws/__init__.py
  lccs_ws/config.py
  lccs_ws/data.py
  lccs_ws/views.py
  setup.py
  tests/lccs_ws_tests/test_app.py
Labels: enhancement

#56 Integration with docker registry and auto deploy
  .drone.yml
Labels: test

#57 Move Dockerfile to the root folder
  DEPLOY.rst
  Dockerfile
  MANIFEST.in
  build.sh
  docker-compose.yml
Labels: test

#59 adding skip null values in classes close #58
  lccs_ws/config.py
  lccs_ws/forms.py
  lccs_ws/views.py
Labels: bug

#60 Minor changes: Improve tests matching with Spec
  .drone.yml
  lccs_ws/jsonschemas/class.json
  lccs_ws/jsonschemas/classe.json
  lccs_ws/jsonschemas/classes.json
  lccs_ws/jsonschemas/classification_system.json
  lccs_ws/jsonschemas/classification_system_type.json
  lccs_ws/jsonschemas/classification_systems.json
  lccs_ws/jsonschemas/exception.json
  lccs_ws/jsonschemas/root.json
  lccs_ws/schemas.py
  lccs_ws/views.py
  setup.py
  tests/json_schemas/classes.json
  tests/json_schemas/classification_systems.json
  tests/lccs_ws_tests/test_app.py
Labels: test

#62 fixing href link in mapping
  lccs_ws/views.py
Labels: bug

#64 Fix Dockerfile command line gunicorn (close #63)
  Dockerfile
Labels: bug
