Repository brazil-data-cube/lccs-ws, pull requests merged in 2021-01, with the labels that each got.

#42 Fixing bug #41 and updating changes
  CHANGES.rst
  docs/sphinx/conf.py
  lccs_ws/version.py
  lccs_ws/views.py
Labels: bug, enhancement

#45 add drone integration close #44
  .drone.yml
  .travis.yml
  README.rst
  pytest.ini
  run-tests.sh
  setup.py
Labels: test

#46 Merge branch b-0.4.0 into master
  .drone.yml
  .travis.yml
  README.rst
  pytest.ini
  run-tests.sh
  setup.py
Labels: release
